services:
  - type: web
    name: btc-dashboard
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: COINBASE_API_KEY
        sync: false
      - key: COINBASE_API_SECRET
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: CRYPTOCOMPARE_KEY
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        sync: false

