# API Configuration
# Copy this file to api_keys_local.yaml and add your actual keys
# Never commit actual API keys to version control

# News APIs
newsapi:
  api_key: "your_newsapi_key_here"
  base_url: "https://newsapi.org/v2"
  
ravenpack:
  api_key: "your_ravenpack_key_here"
  base_url: "https://api.ravenpack.com"

# Financial Data APIs
polygon:
  api_key: "your_polygon_key_here"
  base_url: "https://api.polygon.io"
  
alpaca:
  api_key: "your_alpaca_key_here"
  secret_key: "your_alpaca_secret_here"
  base_url: "https://paper-api.alpaca.markets"  # Use paper trading for testing
  
finnhub:
  api_key: "your_finnhub_key_here"
  base_url: "https://finnhub.io/api/v1"

# Crypto APIs
binance:
  api_key: "your_binance_key_here"
  secret_key: "your_binance_secret_here"
  base_url: "https://api.binance.com"
  
coingecko:
  api_key: "your_coingecko_key_here"  # Optional, has free tier
  base_url: "https://api.coingecko.com/api/v3"

# Social Media APIs
reddit:
  client_id: "your_reddit_client_id"
  client_secret: "your_reddit_client_secret"
  user_agent: "crypto_trading_bot/1.0"
  
twitter:
  bearer_token: "your_twitter_bearer_token"
  api_key: "your_twitter_api_key"
  api_secret: "your_twitter_api_secret"
  access_token: "your_twitter_access_token"
  access_token_secret: "your_twitter_access_token_secret"

# Database
mongodb:
  uri: "mongodb://localhost:27017/crypto_trading"
  
redis:
  host: "localhost"
  port: 6379
  db: 0

# Email (for reports)
smtp:
  host: "smtp.gmail.com"
  port: 587
  username: "your_email@gmail.com"
  password: "your_app_password"
  from_email: "your_email@gmail.com"
  to_emails: ["recipient1@email.com", "recipient2@email.com"]
