# Asset Universe Configuration
# Define the assets to track and analyze

crypto_assets:
  major_coins:
    - symbol: "BTC"
      name: "Bitcoin"
      category: "store_of_value"
      weight: 0.4
    - symbol: "ETH"
      name: "Ethereum"
      category: "smart_contracts"
      weight: 0.3
    - symbol: "BNB"
      name: "Binance Coin"
      category: "exchange_token"
      weight: 0.1
    - symbol: "ADA"
      name: "Cardano"
      category: "smart_contracts"
      weight: 0.05
    - symbol: "SOL"
      name: "Solana"
      category: "smart_contracts"
      weight: 0.05
    - symbol: "DOT"
      name: "Polkadot"
      category: "interoperability"
      weight: 0.05
    - symbol: "AVAX"
      name: "Avalanche"
      category: "smart_contracts"
      weight: 0.05

  altcoins:
    - symbol: "MATIC"
      name: "Polygon"
      category: "layer2"
      weight: 0.02
    - symbol: "LINK"
      name: "Chainlink"
      category: "oracle"
      weight: 0.02
    - symbol: "UNI"
      name: "Uniswap"
      category: "defi"
      weight: 0.02
    - symbol: "AAVE"
      name: "Aave"
      category: "defi"
      weight: 0.01
    - symbol: "SUSHI"
      name: "SushiSwap"
      category: "defi"
      weight: 0.01

stock_assets:
  tech_growth:
    - symbol: "AAPL"
      name: "Apple Inc."
      sector: "Technology"
      weight: 0.15
    - symbol: "MSFT"
      name: "Microsoft Corporation"
      sector: "Technology"
      weight: 0.15
    - symbol: "GOOGL"
      name: "Alphabet Inc."
      sector: "Technology"
      weight: 0.10
    - symbol: "AMZN"
      name: "Amazon.com Inc."
      sector: "Consumer Discretionary"
      weight: 0.10
    - symbol: "TSLA"
      name: "Tesla Inc."
      sector: "Consumer Discretionary"
      weight: 0.08
    - symbol: "NVDA"
      name: "NVIDIA Corporation"
      sector: "Technology"
      weight: 0.08
    - symbol: "META"
      name: "Meta Platforms Inc."
      sector: "Technology"
      weight: 0.05

  financial:
    - symbol: "JPM"
      name: "JPMorgan Chase & Co."
      sector: "Financial Services"
      weight: 0.05
    - symbol: "BAC"
      name: "Bank of America Corp."
      sector: "Financial Services"
      weight: 0.05
    - symbol: "WFC"
      name: "Wells Fargo & Company"
      sector: "Financial Services"
      weight: 0.05
    - symbol: "GS"
      name: "Goldman Sachs Group Inc."
      sector: "Financial Services"
      weight: 0.04

  energy:
    - symbol: "XOM"
      name: "Exxon Mobil Corporation"
      sector: "Energy"
      weight: 0.03
    - symbol: "CVX"
      name: "Chevron Corporation"
      sector: "Energy"
      weight: 0.02

# Market Indices for correlation analysis
indices:
  - symbol: "SPY"
    name: "SPDR S&P 500 ETF"
    type: "etf"
  - symbol: "QQQ"
    name: "Invesco QQQ Trust"
    type: "etf"
  - symbol: "IWM"
    name: "iShares Russell 2000 ETF"
    type: "etf"
  - symbol: "VIX"
    name: "CBOE Volatility Index"
    type: "index"

# News sources configuration
news_sources:
  crypto:
    - name: "CoinDesk"
      rss_url: "https://www.coindesk.com/arc/outboundfeeds/rss/?outputType=xml"
      category: "crypto"
      priority: 1
    - name: "CoinTelegraph"
      rss_url: "https://cointelegraph.com/rss"
      category: "crypto"
      priority: 1
    - name: "Decrypt"
      rss_url: "https://decrypt.co/feed"
      category: "crypto"
      priority: 2
    - name: "The Block"
      rss_url: "https://www.theblock.co/rss.xml"
      category: "crypto"
      priority: 2

  stocks:
    - name: "Yahoo Finance"
      rss_url: "https://feeds.finance.yahoo.com/rss/2.0/headline"
      category: "stocks"
      priority: 1
    - name: "MarketWatch"
      rss_url: "https://feeds.marketwatch.com/marketwatch/topstories/"
      category: "stocks"
      priority: 1
    - name: "Benzinga"
      rss_url: "https://www.benzinga.com/news/feed"
      category: "stocks"
      priority: 2
    - name: "Seeking Alpha"
      rss_url: "https://seekingalpha.com/api/sa/combined/RSS.xml"
      category: "stocks"
      priority: 2

# Trading parameters
trading_params:
  max_position_size: 0.1  # Maximum 10% of portfolio per position
  stop_loss_pct: 0.05     # 5% stop loss
  take_profit_pct: 0.15   # 15% take profit
  rebalance_frequency: 7  # Days between rebalancing
  min_confidence: 0.6     # Minimum confidence for trades
  max_correlation: 0.7    # Maximum correlation between positions

