# Trading Strategy Configuration
# Define different trading strategies and their parameters

strategies:
  btc_ny_session:
    name: "NY Session Strategy"
    description: "Buy at NY open (9:30 AM ET) and sell at NY close (4:30 PM ET)"
    enabled: true
    weight: 0.25
    
    parameters:
      ny_open_hour: 9
      ny_open_minute: 30
      ny_close_hour: 16
      ny_close_minute: 30
      stop_loss_pct: 0.05  # 5% stop loss
      take_profit_pct: 0.05  # 5% take profit
      confidence: 0.80
      
    signals:
      - name: "ny_open_buy"
        weight: 0.5
        description: "Buy signal at NY market open"
      - name: "ny_close_sell"
        weight: 0.5
        description: "Sell signal at NY market close"

  liquidity_sweep_reversal:
    name: "Liquidity Sweep Reversal"
    description: "Detect liquidity hunts beyond swing points with volume confirmation, trade reversal back inside range"
    enabled: true
    weight: 0.25
    
    parameters:
      swing_lookback: 20
      volume_multiplier: 1.5
      body_size_multiplier: 0.8
      stop_buffer: 0.005
      confidence: 0.75
      
    signals:
      - name: "wick_above_swing_short"
        weight: 0.5
        description: "Short signal when wick exceeds swing high with volume"
      - name: "wick_below_swing_long"
        weight: 0.5
        description: "Long signal when wick exceeds swing low with volume"

  volume_weighted_trend_continuation:
    name: "Volume Weighted Trend Continuation"
    description: "Trade trend continuation only when volume confirms real participation using linear regression slope"
    enabled: true
    weight: 0.25
    
    parameters:
      trend_lookback: 20
      volume_lookback: 20
      slope_threshold: 0.0001
      volume_multiplier: 1.2
      confidence: 0.70
      
    signals:
      - name: "uptrend_volume_confirmation"
        weight: 0.5
        description: "Long signal on uptrend with volume confirmation"
      - name: "downtrend_volume_confirmation"
        weight: 0.5
        description: "Short signal on downtrend with volume confirmation"

  volatility_expansion_breakout:
    name: "Volatility Expansion Breakout"
    description: "Detect compression periods, wait for expansion breakout with volume, trade momentum continuation"
    enabled: true
    weight: 0.25
    
    parameters:
      atr_period: 14
      compression_percentile: 30
      body_multiplier: 1.5
      volume_multiplier: 1.3
      trailing_atr_multiplier: 0.5
      confidence: 0.80
      
    signals:
      - name: "compression_breakout_long"
        weight: 1.0
        description: "Long signal on volatility expansion breakout"

# Risk Management Rules
risk_management:
  max_portfolio_var: 0.05  # Maximum 5% daily VaR
  max_drawdown: 0.15  # Maximum 15% drawdown
  position_limits:
    single_asset: 0.1  # Maximum 10% in any single asset
    sector: 0.3  # Maximum 30% in any sector
    crypto: 0.5  # Maximum 50% in crypto
    stocks: 0.7  # Maximum 70% in stocks
  
  stop_loss:
    individual: 0.05  # 5% stop loss per position
    portfolio: 0.10  # 10% portfolio stop loss
    
  take_profit:
    individual: 0.20  # 20% take profit per position
    portfolio: 0.30  # 30% portfolio take profit

# Market Regime Detection
market_regimes:
  bull_market:
    conditions:
      - "fear_greed_index > 60"
      - "vix < 20"
      - "trending_up > 0.6"
    allocation_adjustment:
      crypto: 1.2
      growth_stocks: 1.1
      value_stocks: 0.9
      
  bear_market:
    conditions:
      - "fear_greed_index < 40"
      - "vix > 30"
      - "trending_down > 0.6"
    allocation_adjustment:
      crypto: 0.8
      growth_stocks: 0.8
      value_stocks: 1.1
      bonds: 1.2
      
  high_volatility:
    conditions:
      - "vix > 25"
      - "volatility > 0.3"
    allocation_adjustment:
      crypto: 0.7
      stocks: 0.8
      cash: 1.3
      
  low_volatility:
    conditions:
      - "vix < 15"
      - "volatility < 0.15"
    allocation_adjustment:
      crypto: 1.1
      stocks: 1.1
      cash: 0.9

# Backtesting Configuration
backtesting:
  start_date: "2020-01-01"
  end_date: "2024-01-01"
  initial_capital: 100000  # $100,000
  transaction_costs: 0.001  # 0.1% per trade
  slippage: 0.0005  # 0.05% slippage
  
  metrics:
    - "total_return"
    - "sharpe_ratio"
    - "sortino_ratio"
    - "max_drawdown"
    - "calmar_ratio"
    - "var_95"
    - "cvar_95"
    - "win_rate"
    - "profit_factor"

